### ISSUE TITLE
Quick reply stops working on some apps. 

### ISSUE THREAD

**Issue by Adrianrff** [wasdennnoch/AndroidN-ify#1016]
Build 696(6), Nexus 5, stock 6.0.1.

After installing Android N-ify for the first time, things seems to work just fine, but after a while the quick reply button disappears in some apps, Textra and Gmail in my case. At the time I'm writing this, Textra's  and Gmail's notifications do not have the quick reply option, but whatsapp does. I think I only saw quick reply in Gmail notifications once and then never again. 

The first time this happened I had enabled System UI tuner in Android's settings and got a system UI freeze and crash when trying to edit them (inside Android settings, not Android N-ify), along with a weird boot up (dark screen and only back and home buttons in navbar showing, then system UI restart). I wiped the phone after that and reinstalled everything. I then enabled again System UI tuner in Android's settings and it all happened again (system UI freeze/crash and QR buttons disappearing) but this time disabling System UI tuner brought the quick reply buttons back. However, shortly after they disappeared again. I also tried disabling, uninstalling and reinstalling the module but QR buttons are still not showing.

EDIT: Enabling and disabling System UI tuner (and rebooting) brought the the quick reply feature back after a third try

I didn't get logs the first time, but here's one I took a while ago.

```
10-02 23:10:39.573 I/Xposed  (  325): -----------------
10-02 23:10:39.573 I/Xposed  (  325): Starting Xposed version 86, compiled for SDK 23
10-02 23:10:39.573 I/Xposed  (  325): Device: Nexus 5 (LGE), Android version 6.0.1 (SDK 23)
10-02 23:10:39.573 I/Xposed  (  325): ROM: MOB31E
10-02 23:10:39.573 I/Xposed  (  325): Build fingerprint: google/hammerhead/hammerhead:6.0.1/MOB31E/3142026:user/release-keys
10-02 23:10:39.573 I/Xposed  (  325): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-02 23:10:39.573 I/Xposed  (  325): SELinux enabled: yes, enforcing: yes
10-02 23:10:39.611 I/Xposed  (  325): -----------------
10-02 23:10:39.611 I/Xposed  (  325): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-02 23:10:40.732 I/Xposed  (  325): Detected ART runtime
10-02 23:10:40.780 I/Xposed  (  325): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-02 23:10:41.719 I/Xposed  (  325): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
10-02 23:10:42.559 I/Xposed  (  325):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
10-02 23:10:42.881 I/Xposed  (  325): Loading modules from /data/app/com.ceco.marshmallow.gravitybox-1/base.apk
10-02 23:10:43.517 I/Xposed  (  325):   Loading class com.ceco.marshmallow.gravitybox.GravityBox
10-02 23:10:43.556 I/Xposed  (  325): GB:Hardware: hammerhead
10-02 23:10:43.556 I/Xposed  (  325): GB:Product: hammerhead
10-02 23:10:43.556 I/Xposed  (  325): GB:Device manufacturer: LGE
10-02 23:10:43.556 I/Xposed  (  325): GB:Device brand: google
10-02 23:10:43.556 I/Xposed  (  325): GB:Device model: Nexus 5
10-02 23:10:43.587 I/Xposed  (  325): GB:Device type: phone
10-02 23:10:43.588 I/Xposed  (  325): GB:Is MTK device: false
10-02 23:10:43.588 I/Xposed  (  325): GB:Is Xperia device: false
10-02 23:10:43.588 I/Xposed  (  325): GB:Is Moto XT device: false
10-02 23:10:43.589 I/Xposed  (  325): GB:Has Lenovo custom UI: false
10-02 23:10:43.595 I/Xposed  (  325): GB:Has telephony support: true
10-02 23:10:43.595 I/Xposed  (  325): GB:Has Gemini support: false
10-02 23:10:43.595 I/Xposed  (  325): GB:Android SDK: 23
10-02 23:10:43.595 I/Xposed  (  325): GB:Android Release: 6.0.1
10-02 23:10:43.595 I/Xposed  (  325): GB:ROM: MOB31E
10-02 23:10:43.657 I/Xposed  (  325): Loading modules from /data/app/com.Taptigo.Xposed.XNotifications-1/base.apk
10-02 23:10:43.912 I/Xposed  (  325):   Loading class com.Taptigo.Xposed.XNotifications.Hooks.Hook
10-02 23:10:44.028 I/Xposed  (  325): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
10-02 23:10:44.190 I/Xposed  (  325):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
10-02 23:10:44.231 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Version jenkins-AndroidN-ify-696 (6)
10-02 23:10:44.231 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 696
10-02 23:10:44.231 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Build Time: 2016-09-27T19:53Z
10-02 23:10:44.232 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Git SHA: f2b053aff35e8b8dc36cd4a2892e991d99d0a27c
10-02 23:10:44.247 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: ---- Device info ----
10-02 23:10:44.248 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: SDK Version: 23
10-02 23:10:44.248 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Build ID: MOB31E
10-02 23:10:44.248 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Manufacturer: LGE
10-02 23:10:44.248 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Brand: google
10-02 23:10:44.249 I/Xposed  (  325): [Android N-ify] [INFO] XposedHook: Model: Nexus 5
10-02 23:10:44.249 I/Xposed  (  325): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
10-02 23:10:44.403 I/Xposed  (  325):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
10-02 23:10:44.432 I/Xposed  (  325):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
10-02 23:10:44.433 I/Xposed  (  325): Loading modules from /data/app/com.intangibleobject.securesettings.plugin-1/base.apk
10-02 23:10:44.588 I/Xposed  (  325):   Loading class com.intangibleobject.securesettings.plugin.xposed.Main
10-02 23:10:44.658 E/Xposed  (  325): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.LockSettingsService
10-02 23:10:44.658 E/Xposed  (  325):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
10-02 23:10:44.658 E/Xposed  (  325):   at com.intangibleobject.securesettings.plugin.xposed.a.a(LockSettings.java:35)
10-02 23:10:44.658 E/Xposed  (  325):   at com.intangibleobject.securesettings.plugin.xposed.Main.initZygote(Main.java:31)
10-02 23:10:44.658 E/Xposed  (  325):   at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:436)
10-02 23:10:44.658 E/Xposed  (  325):   at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:361)
10-02 23:10:44.658 E/Xposed  (  325):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
10-02 23:10:44.658 E/Xposed  (  325): Caused by: java.lang.ClassNotFoundException: com.android.server.LockSettingsService
10-02 23:10:44.658 E/Xposed  (  325):   at java.lang.Class.classForName(Native Method)
10-02 23:10:44.658 E/Xposed  (  325):   at java.lang.Class.forName(Class.java:324)
10-02 23:10:44.658 E/Xposed  (  325):   at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
10-02 23:10:44.658 E/Xposed  (  325):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
10-02 23:10:44.658 E/Xposed  (  325):   ... 5 more
10-02 23:10:44.658 E/Xposed  (  325): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.LockSettingsService" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-02 23:10:44.658 E/Xposed  (  325):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-02 23:10:44.658 E/Xposed  (  325):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-02 23:10:44.658 E/Xposed  (  325):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-02 23:10:44.658 E/Xposed  (  325):   ... 9 more
10-02 23:10:44.658 E/Xposed  (  325):   Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.LockSettingsService" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-02 23:10:44.658 E/Xposed  (  325):       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-02 23:10:44.658 E/Xposed  (  325):       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-02 23:10:44.658 E/Xposed  (  325):       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-02 23:10:44.658 E/Xposed  (  325):       ... 10 more
10-02 23:10:44.658 E/Xposed  (  325):       Suppressed: java.lang.ClassNotFoundException: com.android.server.LockSettingsService
10-02 23:10:44.658 E/Xposed  (  325):           at java.lang.Class.classForName(Native Method)
10-02 23:10:44.658 E/Xposed  (  325):           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-02 23:10:44.658 E/Xposed  (  325):           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-02 23:10:44.658 E/Xposed  (  325):           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-02 23:10:44.658 E/Xposed  (  325):           ... 11 more
10-02 23:10:44.658 E/Xposed  (  325):       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-02 23:10:44.658 I/Xposed  (  325): SecureSettings:Initialized
10-02 23:10:46.705 I/Xposed  (  980): GB:Is AOSP forced: false
10-02 23:10:46.812 I/Xposed  (  980): Amplify: Version 3.3.6c
10-02 23:10:46.813 I/Xposed  (  980): Amplify: Attempting 19to21 AlarmHook
10-02 23:10:46.814 I/Xposed  (  980): Amplify: Successful 19to21 AlarmHook
10-02 23:10:46.814 I/Xposed  (  980): Amplify: Attempting 21 WakeLockHook
10-02 23:10:46.815 I/Xposed  (  980): Amplify: Successful 21 WakeLockHook
10-02 23:10:46.815 I/Xposed  (  980): Amplify: Service Blocking Status: true
10-02 23:10:46.815 I/Xposed  (  980): Amplify: Attempting 23 ServiceHook
10-02 23:10:46.816 I/Xposed  (  980): Amplify: Successful 23 ServiceHook
10-02 23:10:58.346 I/Xposed  ( 1119): [Taptigo-XNotifications] Hooking systemUI
10-02 23:10:58.425 I/Xposed  ( 1119): [Taptigo-XNotifications] Headsup is controlled by headsup manager
10-02 23:10:58.547 I/Xposed  ( 1119): [Taptigo-XNotifications][ERROR] Error dumping com.android.systemui.statusbar.policy.HeadsUpNotificationView, Exception: Exception message: Didn't find class "com.android.systemui.statusbar.policy.HeadsUpNotificationView" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/system/priv-app/SystemUI/lib/arm, /vendor/lib, /system/lib]]
10-02 23:10:58.547 I/Xposed  ( 1119): 
10-02 23:10:58.547 I/Xposed  ( 1119):  Stack trace:dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-02 23:10:58.547 I/Xposed  ( 1119): java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-02 23:10:58.547 I/Xposed  ( 1119): java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-02 23:10:58.547 I/Xposed  ( 1119): com.Taptigo.Xposed.XNotifications.Hooks.aw.a(Unknown Source)
10-02 23:10:58.547 I/Xposed  ( 1119): com.Taptigo.Xposed.XNotifications.Hooks.aw.c(Unknown Source)
10-02 23:10:58.547 I/Xposed  ( 1119): com.Taptigo.Xposed.XNotifications.Hooks.aw.a(Unknown Source)
10-02 23:10:58.547 I/Xposed  ( 1119): com.Taptigo.Xposed.XNotifications.Hooks.Hook.handleLoadPackage(Unknown Source)
10-02 23:10:58.547 I/Xposed  ( 1119): de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-02 23:10:58.547 I/Xposed  ( 1119): de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-02 23:10:58.547 I/Xposed  ( 1119): de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-02 23:10:58.547 I/Xposed  ( 1119): de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
10-02 23:10:58.547 I/Xposed  ( 1119): de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-02 23:10:58.547 I/Xposed  ( 1119): android.app.ActivityThread.handleBindApplication(<Xposed>)
10-02 23:10:58.547 I/Xposed  ( 1119): android.app.ActivityThread.-wrap1(ActivityThread.java)
10-02 23:10:58.547 I/Xposed  ( 1119): android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
10-02 23:10:58.547 I/Xposed  ( 1119): android.os.Handler.dispatchMessage(Handler.java:102)
10-02 23:10:58.547 I/Xposed  ( 1119): android.os.Looper.loop(Looper.java:148)
10-02 23:10:58.547 I/Xposed  ( 1119): android.app.ActivityThread.main(ActivityThread.java:5417)
10-02 23:10:58.547 I/Xposed  ( 1119): java.lang.reflect.Method.invoke(Native Method)
10-02 23:10:58.547 I/Xposed  ( 1119): com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-02 23:10:58.547 I/Xposed  ( 1119): com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-02 23:10:58.547 I/Xposed  ( 1119): de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-02 23:10:58.615 I/Xposed  ( 1119): [Taptigo-XNotifications] Global Uncaught Exception handler set
10-02 23:10:58.619 I/Xposed  ( 1119): [Taptigo-XNotifications] HeadsUpNotificationView class not found, trying Marshmallow implementation
10-02 23:10:58.619 I/Xposed  ( 1119): [Taptigo-XNotifications] HeadsUpNotificationView class not found, trying Marshmallow implementation
10-02 23:10:58.633 I/Xposed  ( 1119): [Taptigo-XNotifications] Hooking systemUI finished
10-02 23:11:01.429 I/Xposed  ( 1119): [Taptigo-XNotifications][VERBOSE] ActiveNotificationsWrapper isApplicable: true
10-02 23:11:01.444 I/Xposed  ( 1119): [Taptigo-XNotifications] StatusBarSnoozeNotificationExtender is applicable
10-02 23:11:02.837 I/Xposed  ( 1119): [Taptigo-XNotifications][VERBOSE] Context found after start method
10-02 23:11:03.473 I/Xposed  ( 1954): [Taptigo-XNotifications_GmailInboxMarkAsReadHook] com.google.android.gm loaded
10-02 23:11:05.252 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] WhatsappMarkAsReadHook Receiver hooked
10-02 23:11:06.438 I/Xposed  ( 2094): [Taptigo-XNotifications_SplitNotifications] 
10-02 23:11:06.438 I/Xposed  ( 2094): Found update notifications runnable: com.whatsapp.notification.am
10-02 23:11:06.558 I/Xposed  ( 2094): [Taptigo-XNotifications_SplitNotifications] 
\getConversations method hooked: public static java.util.ArrayList com.whatsapp.rs.b()
10-02 23:11:06.558 I/Xposed  ( 2094): [Taptigo-XNotifications_SplitNotifications] 
\getConversations method hooked: public static java.util.ArrayList com.whatsapp.rs.c()
10-02 23:11:06.559 I/Xposed  ( 2094): [Taptigo-XNotifications_SplitNotifications] 
\getConversations method hooked: public static java.util.ArrayList com.whatsapp.rs.g()
10-02 23:11:06.559 I/Xposed  ( 2094): [Taptigo-XNotifications_SplitNotifications] 
\getConversations method hooked: public static java.util.ArrayList com.whatsapp.rs.i()
10-02 23:11:06.833 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Whatsapp App created, Version: 2.16.275(451402)
10-02 23:11:06.834 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] ConversationsFragment class not found, trying Conversation class
10-02 23:11:06.835 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Adding candidate com.whatsapp.c.bf from method public static android.content.Intent com.whatsapp.Conversation.a(com.whatsapp.c.bf)
10-02 23:11:06.835 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Adding filtered candidate com.whatsapp.c.bf from method public static android.content.Intent com.whatsapp.Conversation.a(android.content.Context,com.whatsapp.c.bf)
10-02 23:11:06.836 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Found single jid holder candidate: class com.whatsapp.c.bf
10-02 23:11:06.847 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Got cached class for version 2.16.275_451402: com.whatsapp.c.c
10-02 23:11:06.847 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Initializing ContactsProvider with class: com.whatsapp.c.c
10-02 23:11:06.850 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook][VERBOSE] Found contacts map field: public final java.util.Map com.whatsapp.c.c.a
10-02 23:11:06.865 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook][VERBOSE] JIDs map initialized with 328 entries
10-02 23:11:06.867 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Refresh method (2nd way): public final void com.whatsapp.App.a(java.lang.String,boolean,com.whatsapp.protocol.by$b,java.lang.Integer)
10-02 23:11:06.868 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] WhatsappMarkAsReadHook initialized successfully
10-02 23:11:06.870 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Checking method public static void com.whatsapp.App.a(java.lang.String,java.lang.String,com.whatsapp.bdd)
10-02 23:11:06.871 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] Verified method public static void com.whatsapp.App.a(java.lang.String,java.lang.String,com.whatsapp.bdd)
10-02 23:11:06.871 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] WhatsappQuickResponseHook.canSendQuickResponse(): true
10-02 23:11:07.381 I/Xposed  ( 2094): [Taptigo-XNotifications_WhatsappMarkAsReadHook] _unseenMsgCountField: public int com.whatsapp.c.bf.s
10-02 23:11:19.781 I/Xposed  ( 1954): [Taptigo-XNotifications_GmailInboxMarkAsReadHook] In hooked receiver GoogleMailDeviceStartupReceiver, GMAIL_MARK_AS_READ_HOOK_KEY not found in intent, invoking original
10-02 23:11:21.781 I/Xposed  ( 3598): [Taptigo-XNotifications_GoogleMessengerMarkAsReadHook] In hooked receiver
10-02 23:11:22.579 I/Xposed  ( 3766): Loading package com.intangibleobject.securesettings.plugin
10-02 23:11:28.295 I/Xposed  ( 4210): [Taptigo-XNotifications_GmailInboxMarkAsReadHook] com.google.android.gm loaded
10-02 23:11:43.288 I/Xposed  ( 2530): [Taptigo-XNotifications_Wearable] com.textra, tag = null, id = 4
10-02 23:11:43.288 I/Xposed  ( 2530): Responder, remote inputs: 1
10-02 23:11:43.288 I/Xposed  ( 2530): Marcar como leído, remote inputs: 0
10-02 23:11:43.288 I/Xposed  ( 2530): Llamar, remote inputs: 0
10-02 23:12:10.316 I/Xposed  ( 1119): [Android N-ify] [INFO] SystemUIHooks: Debug log enabled
10-02 23:12:32.685 I/Xposed  ( 2530): [Taptigo-XNotifications_Wearable] com.textra, tag = null, id = 4
10-02 23:12:32.685 I/Xposed  ( 2530): Responder, remote inputs: 1
10-02 23:12:32.685 I/Xposed  ( 2530): Marcar como leído, remote inputs: 0
10-02 23:12:32.685 I/Xposed  ( 2530): Llamar, remote inputs: 0
10-02 23:12:35.336 I/Xposed  ( 1119): [Android N-ify] [DEBUG] StatusBarHeaderHooks: handl
```

**Comment by Adrianrff** [comment]
Delete please. I accidentally posted this before completing it.

**Comment by Adrianrff** [comment]
Having additional issues with Whatsapp now and not with Textra.. QR dissappeared in Whatsapp ,so I disabled Xnotification and rebooted. Now it's working on whatsapp but not in Textra. 


[xposed_error_20161003_084523.txt](https://github.com/wasdennnoch/AndroidN-ify/files/506242/xposed_error_20161003_084523.txt)

**Comment by wasdennnoch** [comment]
Are you 100% sure it's not caused by Taptigo-XNotifications or ir's just random between reboots? It indeed sounds very weird and the logs contain nothing useful. Note though that you can't use quick reply in (all) apps when there is more than one message, for example WhatsApp only has Quick Reply when there is only one message, same for Gmail. Maybe that's the cause?

**Comment by Adrianrff** [comment]
Yes, I'm aware of the Whatsapp and Gmail limitations with quick reply, but the feature disappears after a reboot in cases were it shouldn't (never in Textra and when a single message is showing in Whatsapp). Everytime I reboot the phone one of those apps will lose the QR functionality from your mod, sometimes is Whatsapp and sometimes Textra, seems random which one it is.

Sometimes rebooting again without doing anything restores the functionality in both apps, but most of the times it doesn't. I have to disable Xnotification, reboot; re-enable it, reboot. And sometimes even that doesn't do the trick. I often find myself rebooting 6+ times in order to get it to work.

I haven't found a pattern and it seems to be happening to other folks in the XDA forum as well.

**Comment by Adrianrff** [comment]
It is totally random, at least as far as I can tell. I'm not sure what is causing it, but it's definitely something with these 2 modules (yours and Xnotification). Once I get it working I'm both apps it is stable though, it won't dissappear again after the next reboot.

**Comment by Maxr1998** [comment]
I'll look into it in the next days, stay tuned.

**Comment by Adrianrff** [comment]
Alright. 

In my case it's easy to reproduce the problem. Installing both modules and rebooting is enough. Maybe it's device specific?

**Comment by Adrianrff** [comment]
@Maxr1998 Any progress on this issue? It seems to be getting worse on each build! I don't mean to be rude or demanding? Just curious. I talked about this with the dev from Xnotification. They're also looking into it.
