### ISSUE TITLE
System ui crash on menu button on recents

### ISSUE THREAD

**Issue by kotofos** [wasdennnoch/AndroidN-ify#1017]
System ui crashes on menu button press when recent apps opened, regardless of quick switch enabled or disabled. Os: CM13 nightly on lg g3 aka d855
[2016-10-03-17-46-11.txt](https://github.com/wasdennnoch/AndroidN-ify/files/506039/2016-10-03-17-46-11.txt)

**Comment by wasdennnoch** [comment]
PLease post your Xposed log too, looks like something went wrong when hooking a layout file.

```
10-03 17:45:44.948 E/AndroidRuntime(13722): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at tk.wasdennnoch.androidn_ify.systemui.recents.navigate.RecentsNavigation$TaskProgress.start(RecentsNavigation.java:236)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at tk.wasdennnoch.androidn_ify.systemui.recents.navigate.RecentsNavigation.navigateRecents(RecentsNavigation.java:198)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at tk.wasdennnoch.androidn_ify.systemui.recents.navigate.RecentsNavigation.launchFocusedTask(RecentsNavigation.java:142)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at tk.wasdennnoch.androidn_ify.systemui.recents.navigate.RecentsNavigation.dismissRecentsToFocusedTaskOrHome(RecentsNavigation.java:95)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at tk.wasdennnoch.androidn_ify.systemui.recents.navigate.RecentsNavigation$5.replaceHookedMethod(RecentsNavigation.java:82)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at com.android.systemui.recents.RecentsActivity.dismissRecentsToFocusedTaskOrHome(<Xposed>)
10-03 17:45:44.948 E/AndroidRuntime(13722): 	at com.android.systemui.recents.RecentsActivity$1.onReceive(RecentsActivity.java:159)
```

**Comment by kotofos** [comment]
```

10-24 23:02:14.935 I/Xposed  (21258): -----------------
10-24 23:02:14.935 I/Xposed  (21258): Starting Xposed version 86, compiled for SDK 23
10-24 23:02:14.935 I/Xposed  (21258): Device: LG-D850 (LGE), Android version 6.0.1 (SDK 23)
10-24 23:02:14.935 I/Xposed  (21258): ROM: cm_d850-userdebug 6.0.1 MOB31E 7ecc2556a1 test-keys
10-24 23:02:14.935 I/Xposed  (21258): Build fingerprint: lge/g3_att_us/g3:4.4.2/KVT49L.D85010d/D85010d.1403173065:user/release-keys
10-24 23:02:14.935 I/Xposed  (21258): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-24 23:02:14.935 I/Xposed  (21258): SELinux enabled: yes, enforcing: yes
10-24 23:02:14.965 I/Xposed  (21258): -----------------
10-24 23:02:14.965 I/Xposed  (21258): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-24 23:02:15.154 I/Xposed  (21258): Detected ART runtime
10-24 23:02:15.166 I/Xposed  (21258): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-24 23:02:15.321 I/Xposed  (21258): Loading modules from /data/app/com.elesbb.xposedinputautocorrectalways-1/base.apk
10-24 23:02:15.461 I/Xposed  (21258):   Loading class com.elesbb.xposedinputautocorrectalways.XposedStuff
10-24 23:02:15.474 I/Xposed  (21258): Loading modules from /data/app/com.thetonyp.batteryshutdownmanager-1/base.apk
10-24 23:02:15.524 I/Xposed  (21258):   Loading class com.thetonyp.batteryshutdownmanager.BatteryDialog
10-24 23:02:15.537 I/Xposed  (21258): Loading modules from /data/app/xeed.xposed.cbppmod-1/base.apk
10-24 23:02:15.590 I/Xposed  (21258):   Loading class xeed.xposed.cbppmod.PhysicalButtonMod
10-24 23:02:15.608 I/Xposed  (21258): Loading modules from /data/app/com.p1ngu1n.volumesteps-1/base.apk
10-24 23:02:15.624 I/Xposed  (21258):   Loading class com.p1ngu1n.volumesteps.AudioMod
10-24 23:02:15.625 I/Xposed  (21258): Loading modules from /data/app/com.mrchandler.disableprox-1/base.apk
10-24 23:02:15.679 I/Xposed  (21258):   Loading class com.mrchandler.disableprox.XposedMod
10-24 23:02:15.687 I/Xposed  (21258): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
10-24 23:02:15.754 I/Xposed  (21258):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
10-24 23:02:17.352 I/Xposed  (21593): PBMC: Android version 23, module version 58
10-24 23:02:17.368 I/Xposed  (21593): PBMC: Debug log is disabled
10-24 23:02:17.388 I/Xposed  (21593): VolumeSteps+: Safe Headset Volume set to 15
10-24 23:02:17.388 I/Xposed  (21593): VolumeSteps+: Volume keys control ringer
10-24 23:02:41.712 I/Xposed  (21593): PBMC: IM instance acquired
10-24 23:02:41.882 I/Xposed  (21593): PBMC: PWM init
10-24 23:02:42.609 I/Xposed  (21593): VolumeSteps+: MAX_STREAM_VOLUME before: [5, 7, 7, 15, 7, 7, 15, 7, 15, 15]
10-24 23:02:42.609 I/Xposed  (21593): VolumeSteps+: MAX_STREAM_VOLUME after: [5, 7, 7, 23, 7, 7, 15, 7, 15, 15]
10-24 23:02:44.705 I/Xposed  (21881): [Android N-ify] [DEBUG] SystemUIHooks: prepareNavigationBarViewHook called
10-24 23:03:08.728 W/Xposed  (24235): Package name for /system/priv-app/Dialer/Dialer.apk had to be retrieved via parser
10-24 23:03:08.764 W/Xposed  (24235): Package name for /system/app/messaging/messaging.apk had to be retrieved via parser
10-24 23:03:08.804 W/Xposed  (24235): Package name for /system/priv-app/Snap/Snap.apk had to be retrieved via parser
10-24 23:03:28.185 I/Xposed  (21593): PBMC: ABC intent
10-24 23:03:39.887 I/Xposed  (21881): [Android N-ify] [DEBUG] RecentsNavigation: launchFocusedTask
10-24 23:03:39.888 I/Xposed  (21881): [Android N-ify] [DEBUG] RecentsNavigation: task found
10-24 23:03:42.004 I/Xposed  (26901): [Android N-ify] [DEBUG] SystemUIHooks: prepareNavigationBarViewHook called
10-24 23:04:01.124 I/Xposed  (26901): [Android N-ify] [DEBUG] RecentsNavigation: launchFocusedTask
10-24 23:04:04.826 I/Xposed  (26901): [Android N-ify] [DEBUG] RecentsNavigation: launchFocusedTask
10-24 23:04:14.903 I/Xposed  (26901): [Android N-ify] [DEBUG] RecentsNavigation: launchFocusedTask
 
```
