### ISSUE TITLE
SystemUI Crash on Alcatel Flash Plus Running Remix F2 AOSP 5.0.2 rom. 

### ISSUE THREAD

**Issue by Takumi87** [wasdennnoch/AndroidN-ify#1043]
[2016-10-13-12-38-50.txt](https://github.com/wasdennnoch/AndroidN-ify/files/526758/2016-10-13-12-38-50.txt)
Here. I duno if i did it right but this was captured while systemui was crashing

**Comment by wasdennnoch** [comment]
Same crash as #1063.

```
10-13 12:38:43.643 E/AndroidRuntime(12242): FATAL EXCEPTION: main
10-13 12:38:43.643 E/AndroidRuntime(12242): Process: com.android.systemui, PID: 12242
10-13 12:38:43.643 E/AndroidRuntime(12242): java.lang.IllegalArgumentException: method com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators [XposedOriginal] argument 3 has type com.mediatek.systemui.ext.IconIdWrapper[], got java.lang.Integer
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators(<Xposed>)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshSignalCluster(NetworkControllerImpl.java:583)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.addSignalCluster(NetworkControllerImpl.java:469)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:906)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3087)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3083)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:512)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:612)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at android.os.Handler.dispatchMessage(Handler.java:111)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at android.os.Looper.loop(Looper.java:194)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at android.app.ActivityThread.main(ActivityThread.java:5536)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at java.lang.reflect.Method.invoke(Native Method)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
10-13 12:38:43.643 E/AndroidRuntime(12242): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by Takumi87** [comment]
Thank you bro. :) so will be fixed next snapshot build? Or? Sorry for the noob questinwn. :)

**Comment by Maxr1998** [comment]
Subscribe to the other issue and help me testing the builds :)

**Comment by Takumi87** [comment]
Will try. Haha. I'm even kinda scared of testing that mediatek fix android n-ify apk. Haha. I am not yet so familiar of how to revert back if things go wrong. But anyway, i will subscribe. 😁
