### ISSUE TITLE
SystemUI Crashs by open Notifications Menu

### ISSUE THREAD

**Issue by Slider-Override** [wasdennnoch/AndroidN-ify#1045]
SystemUI Crashs by open Notifications Menu,

Screen starts to flash, and nothing is working

Tested on Note4 (Stock 6.0.1)

Not sure where i find the LOGs

**Comment by wasdennnoch** [comment]
You need to get a logcat either from an app (like MatLog) (you need root for that) or via your compter with adb.

**Comment by Slider-Override** [comment]
Thanks, i created a Log with MatLog (latest version 715)

On the Recording the systemUI Crashs by Open the notfication bar

https://drive.google.com/file/d/0B9C-DMc9KJ6ieklKdDRoWWw3ZGM/view?usp=drivesdk

Please let me know if you need more.

**Comment by wasdennnoch** [comment]
Samsung stock officially isn't supported and looking at the amount of crashes I probably won't even try, classic Samsung changed everything. You can try to install GoogLock, a new UI by Samsung closer to AOSP, but I don't know on which devices it works. If not then there's nothing I can do.

```
10-23 19:32:14.827 E/Xposed  ( 1594): android.content.res.Resources$NotFoundException: com.android.systemui:dimen/multi_user_avatar_expanded_size
```
+
```
10-23 19:32:17.927 E/Xposed  (11902): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.tuner.TunerService
```
+
```
10-23 19:32:18.027 E/Xposed  (11902): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.SignalController
```
+
```
10-23 19:32:18.047 E/Xposed  (11902): java.lang.NoSuchMethodError: com.android.systemui.statusbar.stack.NotificationStackScrollLayout#setStackTranslation(float)#exact
```
+
```
10-23 19:32:18.077 E/Xposed  (11902): java.lang.NoSuchMethodError: com.android.systemui.recents.RecentsActivity#dismissRecentsToFocusedTaskOrHome(boolean)#exact
```
+
```
10-23 19:32:20.427 E/Xposed  (11902): java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.StatusBarHeaderView#mSettingsButton
```
-->
```
10-23 19:32:49.907 E/AndroidRuntime(13522): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.measure(int, int)' on a null object reference
10-23 19:32:49.907 E/AndroidRuntime(13522): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks.onMeasure(QuickSettingsHooks.java:159)
10-23 19:32:49.907 E/AndroidRuntime(13522): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$6.replaceHookedMethod(QuickSettingsHooks.java:140)
10-23 19:32:49.907 E/AndroidRuntime(13522): 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
10-23 19:32:49.907 E/AndroidRuntime(13522): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-23 19:32:49.907 E/AndroidRuntime(13522): 	at com.android.systemui.qs.QSPanel.onMeasure(<Xposed>)
10-23 19:32:49.907 E/AndroidRuntime(13522): 	at android.view.View.measure(View.java:20151)
```

**Comment by Slider-Override** [comment]
You mean Good lock ?

**Comment by Maxr1998** [comment]
Yes.

**Comment by Slider-Override** [comment]
You are the men, it works with good lock :-) thanks !!!
