### ISSUE TITLE
MediaTek data indicator System UI crash 

### ISSUE THREAD

**Issue by Vality9** [wasdennnoch/AndroidN-ify#1063]
```
E/TelephonyManager( 3986): Error calling ITelephony#getDataEnabled
E/TelephonyManager( 3986): java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.android.internal.telephony.ITelephony.getDataEnabled()' on a null object reference
E/TelephonyManager( 3986): 	at android.telephony.TelephonyManager.getDataEnabled(TelephonyManager.java:3595)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.policy.MobileDataController.isMobileDataEnabled(MobileDataController.java:205)
E/TelephonyManager( 3986): 	at java.lang.reflect.Method.invoke(Native Method)
E/TelephonyManager( 3986): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1213)
E/TelephonyManager( 3986): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.StatusBarHooks$2.afterHookedMethod(StatusBarHooks.java:104)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.policy.MobileDataController.<init>(<Xposed>)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.<init>(NetworkControllerImpl.java:374)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:858)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3139)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3135)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:516)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:611)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/TelephonyManager( 3986): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/TelephonyManager( 3986): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/TelephonyManager( 3986): 	at android.os.Looper.loop(Looper.java:189)
E/TelephonyManager( 3986): 	at android.app.ActivityThread.main(ActivityThread.java:5529)
E/TelephonyManager( 3986): 	at java.lang.reflect.Method.invoke(Native Method)
E/TelephonyManager( 3986): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/TelephonyManager( 3986): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/TelephonyManager( 3986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
E/TelephonyManager( 3986): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
E/AndroidRuntime( 3986): FATAL EXCEPTION: main
E/AndroidRuntime( 3986): Process: com.android.systemui, PID: 3986
E/AndroidRuntime( 3986): java.lang.IllegalArgumentException: method com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators [XposedOriginal] argument 3 has type com.mediatek.systemui.ext.IconIdWrapper[], got java.lang.Integer
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators(<Xposed>)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshSignalCluster(NetworkControllerImpl.java:565)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.addSignalCluster(NetworkControllerImpl.java:451)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:902)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3139)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3135)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:516)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:611)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/AndroidRuntime( 3986): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/AndroidRuntime( 3986): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3986): 	at android.os.Looper.loop(Looper.java:189)
E/AndroidRuntime( 3986): 	at android.app.ActivityThread.main(ActivityThread.java:5529)
E/AndroidRuntime( 3986): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3986): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3986): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/AndroidRuntime( 3986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
E/AndroidRuntime( 3986): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by Maxr1998** [comment]
`E/AndroidRuntime( 4764): java.lang.IllegalArgumentException: method com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators [XposedOriginal] argument 3 has type com.mediatek.systemui.ext.IconIdWrapper[], got java.lang.Integer
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators(<Xposed>)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshSignalCluster(NetworkControllerImpl.java:565)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.policy.NetworkControllerImpl.addSignalCluster(NetworkControllerImpl.java:451)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:902)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3139)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3135)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:516)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:611)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/AndroidRuntime( 4764): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/AndroidRuntime( 4764): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4764): 	at android.os.Looper.loop(Looper.java:189)
E/AndroidRuntime( 4764): 	at android.app.ActivityThread.main(ActivityThread.java:5529)
E/AndroidRuntime( 4764): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4764): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4764): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/AndroidRuntime( 4764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
E/AndroidRuntime( 4764): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)`

**Comment by Maxr1998** [comment]
Please don't open an issue for every build. I see you already reported that in #1036. Just wait for the fix.

**Comment by Maxr1998** [comment]
@Vality9 Could you try this one and report back? You need to unpack the apk from the zip first.
[Nify_MediaTek_fix.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/545793/Nify_MediaTek_fix.apk.zip)

**Comment by Vality9** [comment]
It doesn't work.

**Comment by Maxr1998** [comment]
Logs?

**Comment by Vality9** [comment]
I took an log then forgot to attach.. sorry 😅
[alogcat.2016-10-22-19-14-21+0530.txt](https://github.com/wasdennnoch/AndroidN-ify/files/546206/alogcat.2016-10-22-19-14-21.0530.txt)

**Comment by wasdennnoch** [comment]
Same crash (first one). Do you have a deodexed SystemUI at hand? If not I can also compile a test/log version.

**Comment by Vality9** [comment]
Yeah my phone is deodexed.

**Comment by Maxr1998** [comment]
Then upload that please :P
Although I may have already fixed that in my own sources.
@wasdennnoch, I'll take care of this.

**Comment by Vality9** [comment]
@Maxr1998 Didn't I sent you lol?

**Comment by Maxr1998** [comment]
Could you download the above file and sent me your Xposed logs afterwards?

**Comment by Vality9** [comment]
It's empty.

**Comment by Maxr1998** [comment]
Reboot, and try again. Probably the logs just can't be read. Or send me your logcat.

**Comment by Vality9** [comment]
Is this Logcat same thing which I used to send you before or there is some method to save Xposed's logs separately too? 😮

**Comment by Takumi87** [comment]
Report:

The Nify_Mediatek_fix apk attached here still gave me systemui crash. Do i have to open another issue?

**Comment by Maxr1998** [comment]
@Vality9 it's the same as before.
@Takumi87 the Nify-MT-log.apk.zip doesn't fix the issue yet, it should only provide me some logging. I need Xposed logs or available or the normal device logs, which contain Xposed logs.

**Comment by Takumi87** [comment]
[Uploading Android N-ify MTKLogs.zip…]()
I captured 2 logs-via xposed and catlog to be safe. Hope this helps.

**Comment by Takumi87** [comment]
Here's the logs. I captured from both xposed logs and catlog and i just uploaded it on drive since my internet is shit.

https://drive.google.com/file/d/0B6reUIyJc-MRSEpsVDNKSFhrVXc/view?usp=drivesdk

**Comment by Maxr1998** [comment]
[Nify_MT_test.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/547614/Nify_MT_test.apk.zip)

Ok guys, had a little error in the previous one. Try this and send me your Xposed logs and/or logcat (from catlog app or adb).

**Comment by Takumi87** [comment]
Here are the logs bro. As usual i captured from both xposed logs and catlog. I read the catlog to make sure there's a tk.wassdennoch lines there.😁😂😀 i have difficulty uploading files directly to github so.
https://drive.google.com/file/d/0B6reUIyJc-MRS25Yek5HY2dLVGM/view?usp=drivesdk

**Comment by Maxr1998** [comment]
I think I finally found the error. Try that, and logs as above.

[Nify_fix.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/548065/Nify_fix.apk.zip)

**Comment by Takumi87** [comment]
Wow man that was fast. Cheers! Thanks. 😁😂😀 will try it tomorrow. Time to get some sleep. :)

**Comment by Vality9** [comment]
That one doesn't work for me.

**Comment by Takumi87** [comment]
Tested the build. Still got the systemui crash. 😭

**Comment by Vality9** [comment]
Wtf... I accidently closed...  sorry

**Comment by wasdennnoch** [comment]
lol

**Comment by Vality9** [comment]
Btw, the N-ify fix apk didn't worked for me and Xposed not showing any logs. 
[alogcat.2016-10-24-23-07-34+0530.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548572/alogcat.2016-10-24-23-07-34.0530.txt)

**Comment by Maxr1998** [comment]
Buuuut, it seems the error is a different one!! ^_^
```
E/Xposed  ( 8758): java.lang.NoSuchMethodError: com.android.systemui.statusbar.phone.NotificationPanelView#setVerticalPanelTranslation(float)#exact
E/Xposed  ( 8758): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
E/Xposed  ( 8758): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
E/Xposed  ( 8758): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.NotificationPanelHooks.hook(NotificationPanelHooks.java:163)
E/Xposed  ( 8758): 	at tk.wasdennnoch.androidn_ify.XposedHook.handleLoadPackage(XposedHook.java:130)
E/Xposed  ( 8758): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
E/Xposed  ( 8758): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
E/Xposed  ( 8758): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
E/Xposed  ( 8758): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
E/Xposed  ( 8758): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
E/Xposed  ( 8758): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
E/Xposed  ( 8758): 	at android.app.ActivityThread.access$1500(ActivityThread.java:162)
E/Xposed  ( 8758): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
E/Xposed  ( 8758): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Xposed  ( 8758): 	at android.os.Looper.loop(Looper.java:189)
E/Xposed  ( 8758): 	at android.app.ActivityThread.main(ActivityThread.java:5529)
E/Xposed  ( 8758): 	at java.lang.reflect.Method.invoke(Native Method)
E/Xposed  ( 8758): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/Xposed  ( 8758): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/Xposed  ( 8758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
E/Xposed  ( 8758): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by wasdennnoch** [comment]
That crash above should already be fixed if you are running on LP.

**Comment by Maxr1998** [comment]
@wasdennnoch Nope, I just pushed another fix commit :P

**Comment by Takumi87** [comment]
Do i need to capture another set of logs? Or it's done by someone with identical issue? :) and is this an mtk problem or issue with devices running LP? Nah, just curious. :D

**Comment by Maxr1998** [comment]
No, but I'd really appreicate if you could upload your deodexed SystemUI apk. @Vality9, where did you upload it?

**Comment by Takumi87** [comment]
Ok. Will get on it. Will have to research how to do it tho and how to find out if mine is odexed or deodexed. I will just probably upload the apk to my drive as usual as i am not yet so familiar with dropbox.

**Comment by Takumi87** [comment]
Here bro. I am not sure if it's odexed or deodexed tho.

https://drive.google.com/file/d/0B6reUIyJc-MRYlNRS0F4VVEtaVU/view?usp=drivesdk

**Comment by Vality9** [comment]
@Maxr1998 I uploaded it on Github? If you can't see or get any error then:

 https://drive.google.com/file/d/0B_CaJq66_92SSEplcG9JMm11MjQ/view?usp=drivesdk

**Comment by Takumi87** [comment]
@Vality9
Is that your systemui?

**Comment by Takumi87** [comment]
Oh my bad. It's logcat. Lol

**Comment by Vality9** [comment]
How can I send my System UI? lol?

**Comment by Takumi87** [comment]
@Vality9
Use root explorer or any favorite file manager of yours that has root access. Go to /system and look for the SystemUI.apk and just copy it to another location and zip it and upload. Either to cloud and paste the link or directly here. I just uploaded mine to Drive since i am on mobile. Mobile version of github sucks. Lol

**Comment by Vality9** [comment]
@Takumi87 There you go. https://drive.google.com/file/d/0B_CaJq66_92SYVc0RGNiVmxDZEk/view?usp=drivesdk

**Comment by Takumi87** [comment]
No. You should mention @Maxr1998
I'm no dev. I'm also just a tester like you. 😁😂😀

**Comment by Mikeyangeleo** [comment]
What is the password to the file??? 😕

**Comment by Vality9** [comment]
Thanks for it but it doesn't work. Nevermind, I would delete Xposed(or
N-ify, still not sure what causes the problem but I have Xposed just for
Android N-ify) at some point because it drains my battery so fast and I
can't even use the latest build to get latest features.

**Comment by Takumi87** [comment]
@Mikeyangeleo
What file? My copy of my systemui isnt password protected.

**Comment by Mikeyangeleo** [comment]
What?  I don't understand the question or perhaps the way you wrote it

**Comment by Takumi87** [comment]
You were asking what is the password to the file and i was wondering what you mean?

**Comment by Vality9** [comment]
Soo....no fix?

**Comment by Maxr1998** [comment]
No, more like "No time" :(
I'll get back to it soon enough.

**Comment by Vality9** [comment]
Should I use the Android Nify version which was working for me?

**Comment by Takumi87** [comment]
@Vality9
What version works for you? Funny, with mine only the stable build works. All the snapshots doesnt. :(

**Comment by Vality9** [comment]
The 618 is the most latest one that works for me.

**Comment by Takumi87** [comment]
![screenshot_2016-11-10-09-39-17](https://cloud.githubusercontent.com/assets/22807945/20169205/229f9dfa-a761-11e6-8f60-c1a8865dfb27.png)
Lol. I tried 618 and i didn't get fc but glitches here and there. 😁😂😂

**Comment by Takumi87** [comment]
And

![screenshot_2016-11-10-09-39-17](https://cloud.githubusercontent.com/assets/22807945/20169319/e00071da-a761-11e6-802d-c67e6ea0308f.png)

**Comment by Vality9** [comment]
Yeah it's a bit buggy. Sometimes I feel I should install Nougat based CyanogenMod but Im not sure if I can just flash any ROM on internet or I need one specificly made for this device.

**Comment by Takumi87** [comment]
Roms are device specific as each device uses different socs and gpu. So you'd end up in trouble. My mtk6752m is stuck on kitkat officially but we have L roms up to 5.1.1. No taste of M or even N. 😭

**Comment by Vality9** [comment]
Ohh, I found Unfofical CyanogenMod based on 5.1.1 so no taste of even Marshmallow lol

**Comment by Takumi87** [comment]
Digging this up again. Hehe. 😁😂😂
