### ISSUE TITLE
Battery usage get stuck

### ISSUE THREAD

**Issue by williamsantc** [wasdennnoch/AndroidN-ify#1088]
When I try to open the battery usage, it shows the message "sittings stop working".

**Comment by wasdennnoch** [comment]
(logcat)

**Comment by iChronos** [comment]
i have the same problem, everytime i try to see battery usage my system ui crashes.
[logcat_and_device_info (2).zip](https://github.com/wasdennnoch/AndroidN-ify/files/546611/logcat_and_device_info.2.zip)

**Comment by wasdennnoch** [comment]
That's a very interesting crash. I'll look into it later, it's already getting late here.

```
10-23 22:17:57.461 E/AndroidRuntime(11753): java.util.UnknownFormatConversionException: Conversion: 
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2321)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2315)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2394)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2365)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2298)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter.doFormat(Formatter.java:1071)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter.format(Formatter.java:1042)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.util.Formatter.format(Formatter.java:1011)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.lang.String.format(String.java:1554)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.content.res.Resources.getString(Resources.java:437)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo.getBatteryInfo(BatteryInfo.java:147)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo$2.onPostExecute(BatteryInfo.java:120)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo$2.onPostExecute(BatteryInfo.java:107)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.os.Looper.loop(Looper.java:234)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at java.lang.reflect.Method.invoke(Native Method)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-23 22:17:57.461 E/AndroidRuntime(11753): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by dchito** [comment]
I have this same issue
