### ISSUE TITLE
lp crash build 720 logs attached

### ISSUE THREAD

**Issue by arunverma833** [wasdennnoch/AndroidN-ify#1102]
Tested build 720 crashes occurs sir
Here is log

I/Process ( 5222): Sending signal. PID: 5222 SIG: 9
E/AudioTrack(  631): AudioTrack::set : Exit
D/audio_hw_primary( 5023): select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
D/ACDB-LOADER( 5023): ACDB -> send_audio_cal, acdb_id = 263, path =  0
D/ACDB-LOADER( 5023): ACDB -> send_adm_topology
D/ACDB-LOADER( 5023): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER( 5023): ACDB -> send_audtable
D/ACDB-LOADER( 5023): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER( 5023): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER( 5023): ACDB -> send_audvoltable
D/ACDB-LOADER( 5023): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
D/ACDB-LOADER( 5023): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/audio_hw_primary( 5023): enable_snd_device: snd_device(2: speaker)
W/InputMethodManagerService(  631): Window already focused, ignoring focus gain of: android.view.inputmethod.InputMethodManager$1@855e93e attribute=null, token = android.view.ViewRootImpl$W@1d99639f
D/ConnectivityService(  631): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=11, legacyType=-1, [] ], android.os.BinderProxy@325d8ebe)
W/AudioService(  631): Current remote volume controller died, unregistering
I/StatusBarManagerService(  631): binder died for pkg=com.android.systemui
W/VolumeController(  631): Error calling dismiss
W/VolumeController(  631): android.os.DeadObjectException
W/VolumeController(  631):      at android.os.BinderProxy.transactNative(Native Method)
W/VolumeController(  631):      at android.os.BinderProxy.transact(Binder.java:496)
W/VolumeController(  631):      at android.media.IVolumeController$Stub$Proxy.dismiss(IVolumeController.java:182)
W/VolumeController(  631):      at android.media.AudioService$VolumeController.postDismiss(AudioService.java:6006)
W/VolumeController(  631):      at android.media.AudioService.setVolumeController(AudioService.java:5856)
W/VolumeController(  631):      at android.media.AudioService$3.binderDied(AudioService.java:5865)
W/VolumeController(  631):      at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  631): WIN DEATH: Window{3567cdee u0 com.android.systemui.ImageWallpaper}
W/WallpaperManagerService(  631): Wallpaper service gone: ComponentInfo{com.android.systemui/com.android.systemui.ImageWallpaper}
V/KeyguardServiceDelegate(  631): *** Keyguard disconnected (boo!)
D/ConnectivityService(  631): releasing NetworkRequest NetworkRequest [ id=11, legacyType=-1, [] ]
E/ConnectivityService(  631): RemoteException caught trying to send a callback msg for NetworkRequest [ id=11, legacyType=-1, [] ]
D/WifiService(  631): Client connection lost with reason: 4
D/audio_hw_primary( 5023): enable_audio_route: apply and update mixer path: low-latency-playback
I/ActivityManager(  631): Process com.android.systemui (pid 5222) has died
W/ActivityManager(  631): Scheduling restart of crashed service com.android.systemui/.ImageWallpaper in 0ms
W/ActivityManager(  631): Scheduling restart of crashed service com.android.systemui/.SystemUIService in 0ms
W/ActivityManager(  631): Scheduling restart of crashed service com.android.systemui/.keyguard.KeyguardService in 0ms
I/ActivityManager(  631): Start proc 5280:com.android.systemui/u0a17 for restart com.android.systemui
W/art     (  631): Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied() from ActivityManagerService.java:1230 waiters=0 for 144ms
I/LoadedApk( 5280): No resource references to update in package common
I/LoadedApk( 5280): No resource references to update in package com.frostbit.stylos
I/LoadedApk( 5280): No resource references to update in package com.frostbit.stylos
I/LoadedApk( 5280): No resource references to update in package com.ngocgiap.htcsense
V/SystemUIService( 5280): Starting SystemUI services.
D/TrustManagerService(  631): Removing dead TrustListener.
V/FingerprintService(  63

**Comment by arunverma833** [comment]
Sorry sir 
Here is it 

I/Process ( 5222): Sending signal. PID: 5222 SIG: 9
E/AudioTrack(  631): AudioTrack::set : Exit
D/audio_hw_primary( 5023): select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
D/ACDB-LOADER( 5023): ACDB -> send_audio_cal, acdb_id = 263, path =  0
D/ACDB-LOADER( 5023): ACDB -> send_adm_topology
D/ACDB-LOADER( 5023): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER( 5023): ACDB -> send_audtable
D/ACDB-LOADER( 5023): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER( 5023): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER( 5023): ACDB -> send_audvoltable
D/ACDB-LOADER( 5023): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
D/ACDB-LOADER( 5023): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/audio_hw_primary( 5023): enable_snd_device: snd_device(2: speaker)
W/InputMethodManagerService(  631): Window already focused, ignoring focus gain of: android.view.inputmethod.InputMethodManager$1@855e93e attribute=null, token = android.view.ViewRootImpl$W@1d99639f
D/ConnectivityService(  631): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=11, legacyType=-1, [] ], android.os.BinderProxy@325d8ebe)
W/AudioService(  631): Current remote volume controller died, unregistering
I/StatusBarManagerService(  631): binder died for pkg=com.android.systemui
W/VolumeController(  631): Error calling dismiss
W/VolumeController(  631): android.os.DeadObjectException
W/VolumeController(  631):      at android.os.BinderProxy.transactNative(Native Method)
W/VolumeController(  631):      at android.os.BinderProxy.transact(Binder.java:496)
W/VolumeController(  631):      at android.media.IVolumeController$Stub$Proxy.dismiss(IVolumeController.java:182)
W/VolumeController(  631):      at android.media.AudioService$VolumeController.postDismiss(AudioService.java:6006)
W/VolumeController(  631):      at android.media.AudioService.setVolumeController(AudioService.java:5856)
W/VolumeController(  631):      at android.media.AudioService$3.binderDied(AudioService.java:5865)
W/VolumeController(  631):      at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  631): WIN DEATH: Window{3567cdee u0 com.android.systemui.ImageWallpaper}
W/WallpaperManagerService(  631): Wallpaper service gone: ComponentInfo{com.android.systemui/com.android.systemui.ImageWallpaper}
V/KeyguardServiceDelegate(  631): *** Keyguard disconnected (boo!)
D/ConnectivityService(  631): releasing NetworkRequest NetworkRequest [ id=11, legacyType=-1, [] ]
E/ConnectivityService(  631): RemoteException caught trying to send a callback msg for NetworkRequest [ id=11, legacyType=-1, [] ]
D/WifiService(  631): Client connection lost with reason: 4
D/audio_hw_primary( 5023): enable_audio_route: apply and update mixer path: low-latency-playback
I/ActivityManager(  631): Process com.android.systemui (pid 5222) has died
W/ActivityManager(  631): Scheduling restart of crashed service com.android.systemui/.ImageWallpaper in 0ms
W/ActivityManager(  631): Scheduling restart of crashed service com.android.systemui/.SystemUIService in 0ms
W/ActivityManager(  631): Scheduling restart of crashed service com.android.systemui/.keyguard.KeyguardService in 0ms
I/ActivityManager(  631): Start proc 5280:com.android.systemui/u0a17 for restart com.android.systemui
W/art     (  631): Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied() from ActivityManagerService.java:1230 waiters=0 for 144ms
I/LoadedApk( 5280): No resource references to update in package common
I/LoadedApk( 5280): No resource references to update in package com.frostbit.stylos
I/LoadedApk( 5280): No resource references to update in package com.frostbit.stylos
I/LoadedApk( 5280): No resource references to update in package com.ngocgiap.htcsense
V/SystemUIService( 5280): Starting SystemUI services.
D/TrustManagerService(  631): Removing dead TrustListener.
V/FingerprintService(  63
