### ISSUE TITLE
System ui crash + setting crash checking battery usage

### ISSUE THREAD

**Issue by iChronos** [wasdennnoch/AndroidN-ify#1103]
Everytime I try to see the battery usage in quick settings I get a system ui crash or in setting, baterry, battery udage y get a setting crashed
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548396/logcat.txt)
[device_info.txt](https://github.com/wasdennnoch/AndroidN-ify/files/548397/device_info.txt)

**Comment by wasdennnoch** [comment]
```
10-24 18:27:27.159 E/AndroidRuntime(9336): FATAL EXCEPTION: main
10-24 18:27:27.159 E/AndroidRuntime(9336): Process: com.android.systemui, PID: 9336
10-24 18:27:27.159 E/AndroidRuntime(9336): java.util.UnknownFormatConversionException: Conversion: 
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2321)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2315)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2394)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2365)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2298)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter.doFormat(Formatter.java:1071)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter.format(Formatter.java:1042)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.util.Formatter.format(Formatter.java:1011)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.lang.String.format(String.java:1554)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.content.res.Resources.getString(Resources.java:437)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo.getBatteryInfo(BatteryInfo.java:147)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo$2.onPostExecute(BatteryInfo.java:120)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at tk.wasdennnoch.androidn_ify.extracted.settingslib.BatteryInfo$2.onPostExecute(BatteryInfo.java:107)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.os.Looper.loop(Looper.java:234)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at java.lang.reflect.Method.invoke(Native Method)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-24 18:27:27.159 E/AndroidRuntime(9336): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

```
10-24 18:27:42.624 E/AndroidRuntime(10553): FATAL EXCEPTION: main
10-24 18:27:42.624 E/AndroidRuntime(10553): Process: com.android.settings, PID: 10553
10-24 18:27:42.624 E/AndroidRuntime(10553): java.lang.IllegalArgumentException: text cannot be null
10-24 18:27:42.624 E/AndroidRuntime(10553): 	at android.graphics.Paint.measureText(Paint.java:1545)
10-24 18:27:42.624 E/AndroidRuntime(10553): 	at com.sonymobile.settings.stamina.BatteryTransitionChart.onMeasure(BatteryTransitionChart.java:300)
10-24 18:27:42.624 E/AndroidRuntime(10553): 	at android.view.View.measure(View.java:18880)
[All the view measuring stuff....]
```

**Comment by dchito** [comment]
I'm having this same problem
