### ISSUE TITLE
SystemUI Crash 

### ISSUE THREAD

**Issue by sapthesh** [wasdennnoch/AndroidN-ify#1112]
SystemUI Crash on Latest build #732
Am on LP 5.0 
[2016-10-25-09-08-03.txt](https://github.com/wasdennnoch/AndroidN-ify/files/550458/2016-10-25-09-08-03.txt)

**Comment by sapthesh** [comment]
Duplicate I see others have already uploaded the same issue.

**Comment by sapthesh** [comment]
I have uploaded the systemui for your reference. 
[System UI 5.0-1437584752.zip](https://github.com/wasdennnoch/AndroidN-ify/files/550502/System.UI.5.0-1437584752.zip)

**Comment by atcharatip** [comment]
thank you

**Comment by Maxr1998** [comment]
There's a NPE from a blur module, could you disable it and try again? Please with new logs.

**Comment by sapthesh** [comment]
@Maxr1998 here is the new logs after disabling the BlurUI Module 
[2016-10-26-1.txt](https://github.com/wasdennnoch/AndroidN-ify/files/553603/2016-10-26-1.txt)

**Comment by wasdennnoch** [comment]
This should already be fixed with the latest builds.
```
10-26 19:59:33.353 E/AndroidRuntime(8854): java.lang.IllegalArgumentException: method com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators [XposedOriginal] argument 3 has type com.mediatek.systemui.ext.IconIdWrapper[], got java.lang.Integer
10-26 19:59:33.353 E/AndroidRuntime(8854): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-26 19:59:33.353 E/AndroidRuntime(8854): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-26 19:59:33.353 E/AndroidRuntime(8854): 	at com.android.systemui.statusbar.SignalClusterView.setMobileDataIndicators(<Xposed>)
```

**Comment by sapthesh** [comment]
Still systemui is Crashing. @wasdennnoch I have attached fresh logs. 
[2016-11-06-13-56-nify.txt](https://github.com/wasdennnoch/AndroidN-ify/files/574514/2016-11-06-13-56-nify.txt)
