### ISSUE TITLE
can't add tiles to the drawer 

### ISSUE THREAD

**Issue by mranzy** [wasdennnoch/AndroidN-ify#1137]
10-31 17:54:51.635 V/PhoneStatusBar(1320): setLightsOn(true)
10-31 17:54:53.714 W/ResourceType(1320): For resource 0x7f08011c, entry index(284) is beyond type entryCount(99)
10-31 17:54:53.714 W/ResourceType(1320): Failure getting entry for 0x7f08011c (t=7 e=284) (error -75)
10-31 17:54:53.731 W/Resources(1320): Converting to string: TypedValue{t=0x1c/d=0xde000000 a=1 r=0x10600f0}
10-31 17:54:59.266 E/Xposed  (1320): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-31 17:54:59.266 E/Xposed  (1320): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1213)
10-31 17:54:59.266 E/Xposed  (1320): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks.recreateTiles(QSTileHostHooks.java:478)
10-31 17:54:59.266 E/Xposed  (1320): 	at tk.wasdennnoch.androidn_ify.systemui.qs.customize.QSCustomizer.save(QSCustomizer.java:318)
10-31 17:54:59.266 E/Xposed  (1320): 	at tk.wasdennnoch.androidn_ify.systemui.qs.customize.QSCustomizer.saveAndHide(QSCustomizer.java:264)
10-31 17:54:59.266 E/Xposed  (1320): 	at tk.wasdennnoch.androidn_ify.systemui.qs.customize.QSCustomizer.hide(QSCustomizer.java:255)
10-31 17:54:59.266 E/Xposed  (1320): 	at tk.wasdennnoch.androidn_ify.systemui.qs.customize.QSCustomizer$1.onClick(QSCustomizer.java:146)
10-31 17:54:59.266 E/Xposed  (1320): 	at android.view.View.performClick(View.java:4789)
10-31 17:54:59.266 E/Xposed  (1320): 	at android.view.View$PerformClick.run(View.java:19881)
10-31 17:54:59.266 E/Xposed  (1320): 	at android.os.Handler.handleCallback(Handler.java:739)
10-31 17:54:59.266 E/Xposed  (1320): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-31 17:54:59.266 E/Xposed  (1320): 	at android.os.Looper.loop(Looper.java:135)
10-31 17:54:59.266 E/Xposed  (1320): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
10-31 17:54:59.266 E/Xposed  (1320): 	at java.lang.reflect.Method.invoke(Native Method)
10-31 17:54:59.266 E/Xposed  (1320): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-31 17:54:59.266 E/Xposed  (1320): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-31 17:54:59.266 E/Xposed  (1320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
10-31 17:54:59.266 E/Xposed  (1320): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-31 17:55:00.932 D/PhoneStatusBar(1320): disable: < expand icons* alerts system_info* back home recent clock search >
10-31 17:55:00.954 V/PhoneStatusBar(1320): setLightsOn(true)
10-31 17:55:01.023 W/InputMethodManagerService(740): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@35203534 attribute=null, token = android.os.BinderProxy@21db91d9

**Comment by DDCOON** [comment]
Turn off this module, restart device, edit.

**Comment by paphonbth** [comment]
@mranzy device and rom details?

**Comment by mranzy** [comment]
@paphonbth using cm12.1 on galaxy s3 neo

**Comment by FreakyEnderman** [comment]
@mranzy  Same thing happened to me on my Sony. Using SystemUI tuner (pressing settings shortcut for 30 seconds) seems to solve this issue. Then edit tiles button functions worked normal for me. But still this is a temporary solution.
