### ISSUE TITLE
N drawer settings Crash: Draw Over Apps permission required?

### ISSUE THREAD

**Issue by alexandrumarcel** [wasdennnoch/AndroidN-ify#1159]
Everytime I'm go to Draw Over Apps permission  the setting app crashes and I remember when I tried this in the past I was asked to give perrmision to draw over apps for settings (Not for Android N-ify).

I tried to disable the drawer and give draw over apps permission for settings but the switch was grayed out.

Here is my logcat file: https://docs.google.com/document/d/1o91Ncu58rz04YMlKJyq1GYMw_U4pBWq4n12ARx33gU8/edit

**Comment by wasdennnoch** [comment]
```
D/AndroidRuntime(15138): Shutting down VM
E/AndroidRuntime(15138): FATAL EXCEPTION: main
E/AndroidRuntime(15138): Process: com.android.settings, PID: 15138
E/AndroidRuntime(15138): Theme: themes:{default=, fontPkg:org.cyanogenmod.hexolibre}
E/AndroidRuntime(15138): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(int)' on a null object reference
E/AndroidRuntime(15138): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
E/AndroidRuntime(15138): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
E/AndroidRuntime(15138): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E/AndroidRuntime(15138): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
E/AndroidRuntime(15138): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15138): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(15138): 	at android.app.ActivityThread.main(ActivityThread.java:5475)
E/AndroidRuntime(15138): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15138): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(15138): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime(15138): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
E/AndroidRuntime(15138): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(int)' on a null object reference
E/AndroidRuntime(15138): 	at com.android.settings.applications.ManageApplications.onCreate(ManageApplications.java:264)
E/AndroidRuntime(15138): 	at android.app.Fragment.performCreate(Fragment.java:2198)
E/AndroidRuntime(15138): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
E/AndroidRuntime(15138): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
E/AndroidRuntime(15138): 	at android.app.BackStackRecord.run(BackStackRecord.java:794)
E/AndroidRuntime(15138): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
E/AndroidRuntime(15138): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:562)
E/AndroidRuntime(15138): 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:1081)
E/AndroidRuntime(15138): 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:673)
E/AndroidRuntime(15138): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime(15138): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
E/AndroidRuntime(15138): 	at com.android.settings.SettingsActivity.onCreate(<Xposed>)
E/AndroidRuntime(15138): 	at android.app.Activity.performCreate(Activity.java:7125)
E/AndroidRuntime(15138): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
E/AndroidRuntime(15138): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
E/AndroidRuntime(15138): 	... 10 more
```

**Comment by alexandrumarcel** [comment]
Any updates about this problem?

If you need additional information I'm here to help :p

**Comment by wasdennnoch** [comment]
Just wait :P
