### ISSUE TITLE
Selecting partial screenshot in quick settings immediately restarts phone

### ISSUE THREAD

**Issue by CorvetteCole** [wasdennnoch/AndroidN-ify#1173]
As title says clicking on partial screenshot brings up my boot animation and the phone restarts. My SD card and SIM card don't remount so this seems to be more of a soft reboot. I'm running a Moto X Pure Edition

Build 763

**Xposed log / logcat**
[error.txt](https://github.com/wasdennnoch/AndroidN-ify/files/579209/error.txt)

**Comment by wasdennnoch** [comment]
We need a logcat captured via a computer while you trigger the crash.

**Comment by CorvetteCole** [comment]
Here you go. I'm new to logcats so I just started the logcat, caused the crash, and let the phone reboot before stopping it. Is the attached file what you were looking for?
[partialscreenshotcrash.txt](https://github.com/wasdennnoch/AndroidN-ify/files/579366/partialscreenshotcrash.txt)

**Comment by wasdennnoch** [comment]
It is, thanks.

```ruby
java.lang.NoSuchMethodError: com.android.server.policy.PhoneWindowManagerWithMotoDisplay#takeScreenshot()#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:436)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:449)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1213)
	at tk.wasdennnoch.androidn_ify.android.AndroidHooks$1.onReceive(AndroidHooks.java:25)
```

**Comment by CorvetteCole** [comment]
Awesome, thanks for your awesome work on this module. Keep it up! 👍

**Comment by kushalchauhan98** [comment]
I have the same problem in my MotoE2(4G-LTE))  causing the device to reboot and obtained a similar logcat. 
Hope it'll be solved soon!!

**Comment by wasdennnoch** [comment]
Do you have a deodexed version of your SystemUI at hand?

**Comment by kushalchauhan98** [comment]
Actually I'm a noob(kind of) here. I am running on Stock Marshmallow which is supposedly Odexed. But I cannot find any .odex file in /system/app folder (probably deodexed?). Also, first boot after clearing Dalvik Cache and Cache partition takes a long time showing "Optimizing app x of y" window (probably deodexed?). Anyways, my SystemUI.apk has a 'classes.dex' file inside it which I think indicates that it is a deodexed apk. The apk is inside the zip. Hope it helps!
[SystemUI.zip](https://github.com/wasdennnoch/AndroidN-ify/files/586449/SystemUI.zip)

**Comment by wasdennnoch** [comment]
It's deodexed, but I had a look at it and it doesn't hep here, I ned another framework file (that should be deodexed too as your SysUI already is): the /system/framework/framework.jar. It should contain around 2 classes.dex files.

**Comment by kushalchauhan98** [comment]
I did not find any classes.dex files in my framework.jar. Anyways, here it is(in the zip):
[framework.zip](https://github.com/wasdennnoch/AndroidN-ify/files/586517/framework.zip)

**Comment by kushalchauhan98** [comment]
Looks like the issue is partially resolved in build 783. The crash (or reboot) seems to be fixed but I still can't toggle between partial screenshot and normal screenshot. The quick setting tile is unresponsive to touches and I am unable to switch to normal screenshot.
hope this is fixed soon!

**Comment by wasdennnoch** [comment]
There is no toggle, the tile only activates the partial screenshot once. The crash is fixed but not the issue, I know (better than a reboot though).
There is another framework file that should help, the /system/framework/services.jar (the only one that helps but I'm a dummy). Only post it if it contains a classes.dex, otherwise it's useless.

**Comment by kushalchauhan98** [comment]
Sorry for the late reply. Yes, the framework file does contain a classes.dex. 
Here it is(in the zip):
[services.zip](https://github.com/wasdennnoch/AndroidN-ify/files/612570/services.zip)
Hope you add the toggle to switch between partial and normal screenshot soon!
