### ISSUE TITLE
Too many error on Xperia Z5

### ISSUE THREAD

**Issue by solirf** [wasdennnoch/AndroidN-ify#1218]
11-15 22:31:13.549 I/Xposed  ( 1493): -----------------
11-15 22:31:13.549 I/Xposed  ( 1493): Starting Xposed version 86, compiled for SDK 23
11-15 22:31:13.549 I/Xposed  ( 1493): Device: E6633 (Sony), Android version 6.0.1 (SDK 23)
11-15 22:31:13.549 I/Xposed  ( 1493): ROM: 32.2.A.0.305
11-15 22:31:13.549 I/Xposed  ( 1493): Build fingerprint: Sony/E6633/E6633:6.0.1/32.2.A.0.305/724807262:user/release-keys
11-15 22:31:13.549 I/Xposed  ( 1493): Platform: arm64-v8a, 64-bit binary, system server: yes
11-15 22:31:13.549 I/Xposed  ( 1493): SELinux enabled: yes, enforcing: yes
11-15 22:31:14.581 I/Xposed  ( 1493): -----------------
11-15 22:31:14.584 I/Xposed  ( 1493): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-15 22:31:15.037 I/Xposed  ( 1493): Detected ART runtime
11-15 22:31:15.061 I/Xposed  ( 1493): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-15 22:31:15.425 I/Xposed  ( 1493): Loading modules from /data/app/xda.dully79.xposeddtndisabler-1/base.apk
11-15 22:31:15.557 I/Xposed  ( 1493):   Loading class xda.dully79.xposeddtndisabler.dtnDisabler
11-15 22:31:15.558 I/Xposed  ( 1493): Loading modules from /data/app/net.local.hidesimicons-1/base.apk
11-15 22:31:15.588 I/Xposed  ( 1493):   Loading class net.local.hidesimicons.Hooks
11-15 22:31:15.591 I/Xposed  ( 1493): Loading modules from /data/app/michele2.xperia.staminahide-1/base.apk
11-15 22:31:15.637 I/Xposed  ( 1493):   Loading class michele2.xperia.staminahide.Xposed
11-15 22:31:15.638 I/Xposed  ( 1493): Loading modules from /data/app/com.ssrdroide.qsxtilesperrow-1/base.apk
11-15 22:31:15.720 I/Xposed  ( 1493):   Loading class com.ssrdroide.qsxtilesperrow.XposedQsxtilesperrow
11-15 22:31:15.782 I/Xposed  ( 1493): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
11-15 22:31:15.806 I/Xposed  ( 1493):   Loading class ma.wanam.youtubeadaway.Xposed
11-15 22:31:15.809 I/Xposed  ( 1493): Loading modules from /data/app/com.ihelp101.instagram-2/base.apk
11-15 22:31:15.877 I/Xposed  ( 1493):   Loading class com.ihelp101.instagram.Module
11-15 22:31:15.927 I/Xposed  ( 1493): Loading modules from /data/app/serajr.sum.x-1/base.apk
11-15 22:31:15.945 I/Xposed  ( 1493):   Loading class serajr.sum.x.Xposed
11-15 22:31:15.945 I/Xposed  ( 1493): Loading modules from /data/app/com.pavlyukoff.xposed.fingerprintenabler-1/base.apk
11-15 22:31:15.962 I/Xposed  ( 1493):   Loading class com.pavlyukoff.xposed.fingerprintenabler.XposedClass
11-15 22:31:15.965 I/Xposed  ( 1493): Loading modules from /data/app/com.sabik.assistantenabler-1/base.apk
11-15 22:31:16.034 I/Xposed  ( 1493):   Loading class com.sabik.assistantenabler.AssistantEnabler
11-15 22:31:16.054 I/Xposed  ( 1493): Loading modules from /data/app/tk.wasdennnoch.androidn_ify-1/base.apk
11-15 22:31:16.125 I/Xposed  ( 1493):   Loading class tk.wasdennnoch.androidn_ify.XposedHook
11-15 22:31:16.150 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: Version jenkins-AndroidN-ify-776 (6)
11-15 22:31:16.150 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: Automated Build; Version: 776
11-15 22:31:16.150 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: Build Time: 2016-11-13T15:39Z
11-15 22:31:16.150 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: Git SHA: 1175fb4fa84272d4a6174e69262e8406a9b44b8c
11-15 22:31:16.158 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: ---- Device info ----
11-15 22:31:16.158 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: SDK Version: 23
11-15 22:31:16.158 I/Xposed  ( 1493): [Android N-ify] [INFO] XposedHook: Build ID: 32.2.A.0.305
11-15 22:32:15.706 E/Xposed  ( 4771): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
11-15 22:32:15.706 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedHelpers.getIntField(XposedHelpers.java:928)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.NotificationPanelHooks.getStatusBarState(NotificationPanelHooks.java:174)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks.updateBackgroundBounds(NotificationStackScrollLayoutHooks.java:535)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks.updateBackground(NotificationStackScrollLayoutHooks.java:340)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks.access$000(NotificationStackScrollLayoutHooks.java:42)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks$8.afterHookedMethod(NotificationStackScrollLayoutHooks.java:184)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.applyCurrentState(<Xposed>)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateChildren(NotificationStackScrollLayout.java:450)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateChildren(<Xposed>)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.access$000(NotificationStackScrollLayout.java:66)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout$1.onPreDraw(NotificationStackScrollLayout.java:224)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2059)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.os.Handler.handleCallback(Handler.java:739)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.os.Looper.loop(Looper.java:234)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at java.lang.reflect.Method.invoke(Native Method)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-15 22:32:15.706 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
11-15 22:32:15.949 I/Xposed  ( 5220): QsXTilesPerRow ==========>>> Module loaded! Debug mode: false
11-15 22:32:15.954 I/Xposed  ( 5227): QsXTilesPerRow ==========>>> Module loaded! Debug mode: false
11-15 22:32:15.967 I/Xposed  ( 5220): HideSimIcon: Detected M 6.0
11-15 22:32:15.967 I/Xposed  ( 5227): HideSimIcon: Detected M 6.0
11-15 22:32:19.153 E/Xposed  ( 4771): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
11-15 22:32:19.153 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedHelpers.getIntField(XposedHelpers.java:928)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.NotificationPanelHooks.getStatusBarState(NotificationPanelHooks.java:174)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks.updateBackgroundBounds(NotificationStackScrollLayoutHooks.java:535)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks.updateBackground(NotificationStackScrollLayoutHooks.java:340)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks.access$000(NotificationStackScrollLayoutHooks.java:42)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at tk.wasdennnoch.androidn_ify.systemui.notifications.stack.NotificationStackScrollLayoutHooks$8.afterHookedMethod(NotificationStackScrollLayoutHooks.java:184)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.applyCurrentState(<Xposed>)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateChildren(NotificationStackScrollLayout.java:450)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.updateChildren(<Xposed>)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.access$000(NotificationStackScrollLayout.java:66)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout$1.onPreDraw(NotificationStackScrollLayout.java:224)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2059)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
11-15 22:32:19.153 E/Xposed  ( 4771): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)

**Comment by wasdennnoch** [comment]
Do these appear only after a reboot or every time you receive a notification?

**Comment by solirf** [comment]
complete log :
[xposed_error_20161202_031322.txt](https://github.com/wasdennnoch/AndroidN-ify/files/626009/xposed_error_20161202_031322.txt)

also AndroidN-ify app crash when i open it (lastest version )

**Comment by solirf** [comment]
It apper after reboot
