### ISSUE TITLE
System UI crash on HTC D820F 6.0.1

### ISSUE THREAD

**Issue by kirbyloco** [wasdennnoch/AndroidN-ify#1219]
**Description**
System UI crash
**Module version (build version)**
snapshot 779
**Xposed log / logcat**
[android logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/594625/android.logcat.txt)

**Comment by wasdennnoch** [comment]
HTC stock isn't supported. To avoid this crash you'll have to disable the header tweaks.
```
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.measure(int, int)' on a null object reference
E AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks.onMeasure(QuickSettingsHooks.java:189)
AndroidRuntime: 	at tk.wasdennnoch.androidn_ify.systemui.qs.QuickSettingsHooks$8.replaceHookedMethod(QuickSettingsHooks.java:170)
```
