### ISSUE TITLE
Build 808 Crash when opening settings

### ISSUE THREAD

**Issue by char101** [wasdennnoch/AndroidN-ify#1304]
**Description**
Crash when opening settings

**Module version (build version)**
808

**Xposed log / logcat**
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
at tk.wasdennnoch.androidn_ify.utils.MiscUtils.checkValidJSONArray(MiscUtils.java:36)
at tk.wasdennnoch.androidn_ify.ui.SettingsActivity$Fragment$1.onLoadFinished(SettingsActivity.java:195)
at tk.wasdennnoch.androidn_ify.ui.SettingsActivity$Fragment$1.onLoadFinished(SettingsActivity.java:165)
at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
at android.content.Loader.deliverResult(Loader.java:144)
at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by char101** [comment]
OS: CM 13.1

**Comment by Maxr1998** [comment]
@char101 could you post full log? I wonder why it even throws an `IOException` at `loadInBackground()`.

**Comment by char101** [comment]
@Maxr1998 I don't see any `IOException` or `loadInBackground()` in the stack trace above.
