### ISSUE TITLE
OxygenOS 3.2.1 Compatibility

### ISSUE THREAD

**Issue by tbremer19** [wasdennnoch/AndroidN-ify#613]
Hi! First of all, awesome module! Great work, I love it!
Unfortunately it's pretty unusable on the OnePlus 3 with OOS 3.2.1. Quick Settings look wrong and the whole SystemUI crashes when you click on the recents button.
Here's the log for that:
```
--------- beginning of crash
07-20 21:52:58.416  1954  1954 E AndroidRuntime: FATAL EXCEPTION: main
07-20 21:52:58.416  1954  1954 E AndroidRuntime: Process: com.android.systemui, PID: 1954
07-20 21:52:58.416  1954  1954 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.systemui/com.android.systemui.recents.RecentsActivity}: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to com.android.systemui.recents.views.RecentsEmptyView
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2456)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:159)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:152)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5507)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to com.android.systemui.recents.views.RecentsEmptyView
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at com.android.systemui.recents.RecentsActivity.onCreate(RecentsActivity.java:417)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6304)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2409)
07-20 21:52:58.416  1954  1954 E AndroidRuntime: 	... 10 more
```

![Image](https://dl2.pushbulletusercontent.com/fKPtk5j0BYtx7D160f5f33PFBtU7cGwt/Screenshot_20160720-215010.png)

**Comment by wasdennnoch** [comment]
To fix the crash disable the N "no recents" image. The edit button is a known issue in OOS3, the problem is that I haven't found a deodexed SystemUI yes, so I can't fix it because I don't have any code they use. What do you mean with "QS look wrong"?

**Comment by tbremer19** [comment]
Thank you, I just meant the background color, it's darker than the header.
Can I do anything for you regarding the OOS SystemUI apk?

**Comment by wasdennnoch** [comment]
These things already have other issues open except for the first row enlargement, but OOS probably again changed that and I can't fix that right now, I'll cloe this as it's not that "bad" and, well, I can't fix it :P

**Comment by tbremer19** [comment]
I hope that helps. If not, tell me what I can do to help you ;)
[SystemUI.zip](https://github.com/wasdennnoch/AndroidN-ify/files/404455/SystemUI.zip)

**Comment by wasdennnoch** [comment]
@tbremer19 I guess you used basksmali to decompile? You'd have to run smali after that to convert the smali code to java code. I already have another OOS SystemUI, but can't find anything related to this issue.
