### ISSUE TITLE
System UI crash CM12.1

### ISSUE THREAD

**Issue by Bajista58** [wasdennnoch/AndroidN-ify#665]
Facing system UI crash on boot after enabling the module
[logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/402197/logcat.txt)

**Comment by wasdennnoch** [comment]
Yes yes, the Visualizer tile is evil... I had the same crash, will try to fix it although it isn't really caused by the module.

```
E/AndroidRuntime(11567): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator com.pheelicks.visualizer.VisualizerView.animate()' on a null object reference
E/AndroidRuntime(11567): 	at com.android.systemui.qs.tiles.VisualizerTile$5.run(VisualizerTile.java:245)
E/AndroidRuntime(11567): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(11567): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(11567): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11567): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(11567): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11567): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11567): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(11567): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(11567): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by wasdennnoch** [comment]
Added with c5f03a1689d10fd15be65f2c833fbd6d93bdc668
