### ISSUE TITLE
SystemUI crash when opening recents on OOS

### ISSUE THREAD

**Issue by shyim** [wasdennnoch/AndroidN-ify#680]
Newest xposed
Android 6.0.1

```
08-15 19:02:37.309  6294  6294 D AndroidRuntime: Shutting down VM
08-15 19:02:37.309  6294  6294 E AndroidRuntime: FATAL EXCEPTION: main
08-15 19:02:37.309  6294  6294 E AndroidRuntime: Process: com.android.systemui, PID: 6294
08-15 19:02:37.309  6294  6294 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.systemui/com.android.systemui.recents.RecentsActivity}: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to com.android.systemui.recents.views.RecentsEmptyView
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2456)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.ActivityThread.access$900(ActivityThread.java:159)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:152)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5507)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
08-15 19:02:37.309  6294  6294 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to com.android.systemui.recents.views.RecentsEmptyView
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at com.android.systemui.recents.RecentsActivity.onCreate(RecentsActivity.java:417)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:6304)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2409)
08-15 19:02:37.309  6294  6294 E AndroidRuntime:    ... 10 more
08-15 19:02:37.313  6294  6294 D AppTracker: App Event: crash
```

**Comment by wasdennnoch** [comment]
Are you on OOS? If so, disable the no recents image to fix it.

**Comment by shyim** [comment]
It fixed it lol. What means "OOS" :D

**Comment by wasdennnoch** [comment]
OOS = OxygenOS, the ROM on OnePlus phones. The crash is a known issue, but not easy to fix. They use an own view to manage the "no recents" screen and reference it in many places in the code, but the module removes this view, so it crashes. 

btw, can you please send a screenshot of the normal no recents screen? because I don't know how it looks like on OOS, and they seem to have added a bunch of stuff to it.

**Comment by shyim** [comment]
![Screenshot_20160815-215004.png](http://i.imgur.com/9aMXDeB.jpg)

**Comment by wasdennnoch** [comment]
The empty recents, when there aren't any (after you pressed the clear button) ;)

**Comment by shyim** [comment]
![Screenshot_20160815-215458.png](http://i.imgur.com/i63leVp.jpg)

**Comment by wasdennnoch** [comment]
Thanks, nice squirrel in the status bar btw :P

**Comment by ttimz1313** [comment]
No problem. It's under construction still I'm working on it.  And I'm just
some dude
